sudo: enabled
language: cpp
dist: trusty
os:
  - linux
  - osx

notifications:
  email: false

before_install:
 - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
     sudo add-apt-repository -y ppa:beineri/opt-qt59-trusty;
     sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
     sudo apt-get update;
     sudo apt-get install -y g++-7 cmake;
     echo "g++-7 done.";
     sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90;
     sudo update-alternatives --set g++ "/usr/bin/g++-7";
     g++ --version;
     sudo apt-get install qt59-meta-full;
     echo "qt59-meta-full done.";
     QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh');
     source $QT_ENV_SCRIPT;
   fi
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
     brew install qt cmake;
     brew link qt --force;
   fi

script:
 - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
     PREFIX=/usr;
   fi
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
     PREFIX=/usr/local;
   fi
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX
 - make
 - sudo make install

